# Generated by Django 5.2.6 on 2025-11-05 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_gestao', '0002_alter_gestao_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=11)),
                ('validade_em_meses', models.PositiveIntegerField(choices=[(3, '3 meses'), (6, '6 meses'), (12, '12 meses'), (18, '18 meses'), (24, '24 meses'), (36, '36 meses')], default=6)),
                ('quantidade_horas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TreinamentoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_treinamento', models.DateField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_gestao.gestao')),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_treinamento.treinamento')),
            ],
        ),
    ]
